apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-backend-deployment
spec:
  selector:
    matchLabels:
      app: chat-backend-deployment
  template:
    metadata:
      labels:
        app: chat-backend-deployment
    spec:
      containers:
      - name: chat-backend-deployment
        image: kobi070/chatapp-backend-service:latest
        ports:
        - containerPort: 3001
