apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp-web-servie
spec:
  selector:
    matchLabels:
      app: chatapp-web-servie
  template:
    metadata:
      labels:
        app: chatapp-web-servie
    spec:
      containers:
      - name: chatapp-web-service
        image: kobi070/chatapp-web-servie:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
