apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp-frontend-servie
spec:
  selector:
    matchLabels:
      app: chatapp-frontend-servie
  template:
    metadata:
      labels:
        app: chatapp-frontend-servie
    spec:
      containers:
        - name: chatapp-frontend-service
          image: kobi070/chatapp-web-service
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
