apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-frontend-deployment
  labels:
    app: chat-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-frontend
  template:
    metadata:
      labels:
        app: chat-frontend
      spec:
        containers:
          - name: chat-frontend
            image: kobi070/chatapp-web-servie:latest
            ports:
              - containerPort: 3000